# Generated by Django 2.2 on 2019-07-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190703_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ['priority']},
        ),
        migrations.RenameField(
            model_name='banners',
            old_name='position',
            new_name='priority',
        ),
    ]
