# Generated by Django 2.2 on 2019-07-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190703_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ['-priority']},
        ),
    ]
